before_script: "sudo aptitude -y -q install libcairo2-dev libpixman-1-dev libpango1.0-dev libgif-dev libjpeg-dev libgtk2.0-dev vlc libvlc-dev portaudio19-dev libsqlite3-dev libcurl4-openssl-dev makeself curl"
language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec